version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/src/caddy"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 45
  - package-ecosystem: "docker"
    directory: "/src/fastapi"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 45
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 45
  - package-ecosystem: "pip"
    directory: "/src/fastapi"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 45
